### ISSUE TITLE
podfile needs target for cocoapods 1.0.1

### ISSUE THREAD

**Issue by a75c6** [flurry/YodeliOSApp#9]
So:

target 'YodelSample' do
pod 'TMTumblrSDK'
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'Flurry-iOS-SDK/FlurryAds'
end

**Comment by rollinsio** [comment]
Thanks @namsoila.  Feel free to submit a PR if you'd like, otherwise, I'll get to it in the next few days.

**Comment by rollinsio** [comment]
Done.
